### PR TITLE
sgd and minimize should return void.

### PR DESCRIPTION
**Pull request by ry**
To answer #439

### CODE REVIEW

**Comment by indutny** [comment]
What about `maybeSave` it seems to be doing something weird if not being awaited.

**Comment by ry** [comment]
The idea was that it would save in the background to not block training. What is the weirdness?

**Comment by indutny** [comment]
At times it saves several times in a row for consecutive sequence ids.

**Comment by ry** [comment]
@indutny is that when you restart the process? Because it's told to save when the process exits, and when training starts. So restarting would cause that...

**Comment by indutny** [comment]
No, it seems to just randomly happen from time to time during the learning, unless I've an await.

**Pull request merged**
