### PR TITLE
Update main.scss

### PR DESCRIPTION
**Pull request by Qti3e**
When user clicked on the CodeMirror, the scroll bar showed itself

### CODE REVIEW

**Comment by ry** [comment]
Thanks for the bug fix!

What browser are you using? I don't experience the scroll bar issue on Chrome.

**Comment by Qti3e** [comment]
Hi
```
Chromium	63.0.3239.84 (Official Build) Built on Ubuntu , running on Ubuntu 16.04 (64-bit)
Revision	0f53a5abc7a405fbe9f1cfd3db38f2092c8a7816-
OS	Linux
JavaScript	V8 6.3.292.46
Flash	(Disabled)
User Agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/63.0.3239.84 Chrome/63.0.3239.84 Safari/537.36
Command Line	/usr/lib/chromium-browser/chromium-browser --enable-pinch --proxy-pac-url=file:///home/qti3e/proxy.pac --flag-switches-begin --flag-switches-end
Executable Path	/usr/lib/chromium-browser/chromium-browser
Profile Path	/home/qti3e/.config/chromium/Profile 1
```

**Comment by ry** [comment]
Ok - I guess it's not a browser incompatibility then. How do I reproduce the scroll bar error?

**Comment by Qti3e** [comment]
Well, I recheck the website in incognito mode (with no browser extensions) and there was no problem,
maybe the problem is with one of my too many extensions :)
I close this request

**Pull request closed without merging**
